### ISSUE TITLE
Content has not bean provided

### ISSUE THREAD

**Issue by zsf513** [aliyun/aliyun-openapi-java-sdk#194]
使用4.3.5版本发送短信时报“Content has not bean provided"的错误。代码不变，将版本降低至4.0.6或4.3.4时，就可以发送成功！
环境:mac 10.14.3，jdk1.8

**Comment by JacksonTian** [comment]
您好。请您提供一下完整的错误堆栈。
将包暂时固定在 4.3.4。我们修复完成后，再升级。

**Comment by taurencoder** [comment]
Meeting exactly the same issue.
`java.lang.IllegalStateException: Content has not been provided
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.entity.BasicHttpEntity.getContent(BasicHttpEntity.java:75)
	at org.apache.http.entity.BasicHttpEntity.writeTo(BasicHttpEntity.java:112)
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.aliyuncs.http.clients.ApacheHttpClient.syncInvoke(ApacheHttpClient.java:230)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:245)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:173)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:70)
	at com.aliyuncs.DefaultAcsClient.getCommonResponse(DefaultAcsClient.java:137)
	at com.stonelens.starter.message.SmsService.sendMessage(SmsService.kt:62)
	at com.stonelens.starter.message.SmsService.sendVerificationMessage(SmsService.kt:27)
	at com.stonelens.starter.message.SmsService$$FastClassBySpringCGLIB$$f123257a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by ssy352959096** [comment]
您好，已经修复，请升级依赖至4.3.7
