### ISSUE TITLE
4.3 以上版本由于添加了 resource 文件，spring boot fat jar 不能加载project.properties

### ISSUE THREAD

**Issue by lizecn** [aliyun/aliyun-openapi-java-sdk#237]
由于 spring fat jar 加载方式导致， jar in jar 不能加载resource 中的project.properties，
在UserAgentConfig中需要考虑这种fat jar 的兼容性。

java.lang.ExceptionInInitializerError
	at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:47)
	at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:56)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Unknown Source)
	at java.util.Properties.load0(Unknown Source)
	at java.util.Properties.load(Unknown Source)
	at com.aliyuncs.http.UserAgentConfig.<clinit>(UserAgentConfig.java:13)
	... 10 more

**Comment by atptro** [comment]
您好如果是project.properties加载问题在新的版本已经解决，请更新到最新的版本4.4.0

**Comment by lizecn** [comment]
升级到最新版4.4， solved
