### ISSUE TITLE
client.getAcsResponse(request) 偶发异常

### ISSUE THREAD

**Issue by hyuming** [aliyun/aliyun-openapi-java-sdk#240]
* **产品和接口**:
* **平台**:
Java
* **最小代码**:
获取视频播放URL请求，client.getAcsResponse(request) 调用偶尔发生reponse解析异常问题。
但是同一个参数再次测试调用，结果正常。频率不算低， 十几分钟出现一次

java.lang.IllegalStateException: Server response has a bad format type: RAW
        at com.aliyuncs.reader.ReaderFactory.createInstance(ReaderFactory.java:16)
        at com.aliyuncs.DefaultAcsClient.readResponse(DefaultAcsClient.java:314)
        at com.aliyuncs.DefaultAcsClient.parseAcsResponse(DefaultAcsClient.java:199)
        at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:115)
        at xx.xxx.model.service.AliyunVideoUploadService.requestAndCacheAliyunPlayInfo(AliyunVideoUploadService.java:112)
        at xx.xxx.model.service.AliyunVideoUploadService.getPlayInfoUrl(AliyunVideoUploadService.java:85)
        at xx.xxx..model.service.AliyunVideoUploadService$$FastClassBySpringCGLIB$$c2d53aea.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)

**Comment by hyuming** [comment]
提错位置

**Comment by hyuming** [comment]
aliyun-java-sdk-core  中  DefaultAcsClient.getAcsResponse(request)

**Comment by ssy352959096** [comment]
您好，请将core升级至最新版本4.4.0和尝试 `request.setAcceptFormat(FormatType.JSON)；`
