### ISSUE TITLE
Cannot make request on Android using ECS SDK

### ISSUE THREAD

**Issue by eneim** [aliyun/aliyun-openapi-java-sdk#258]
* **Product and API**: ECS SDK 4.16.10, Core SDK 4.4.2
* **Platform**: Android (Android 8.1)
* **Mininum Code**: (provided below)

Hi there, I'm having an issue when using the SDK on Android. Below are the issues and my attempts:

The first issues is when using default Apache Http Client, it throws:

<details>

<summary>
<strong>java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier</strong>
</summary>

```shell
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes2.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
        at com.aliyuncs.http.clients.ApacheHttpClient.createSSLConnectionSocketFactory(ApacheHttpClient.java:120)
        at com.aliyuncs.http.clients.ApacheHttpClient.initConnectionManager(ApacheHttpClient.java:134)
        at com.aliyuncs.http.clients.ApacheHttpClient.init(ApacheHttpClient.java:184)
        at com.aliyuncs.http.HttpClientFactory.buildClient(HttpClientFactory.java:41)
        at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:77)
        at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:66)
        at EcsViewModel.<init>(EcsViewModel.kt:42)
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:182)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:241)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:164)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:130)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at MainActivity.getViewModel(Unknown Source:7)
        at MainActivity.onCreate(MainActivity.kt:90)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
</details>

As Android removed ``AllowAllHostnameVerifier`` from its binary, this issue is expected. So I try to config my Client to use ``HttpClientType.Compatible``. Using this client, it then throws the following issues:

<details>
<summary>
<strong>
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String javax.xml.bind.DatatypeConverterInterface.printBase64Binary(byte[])' on a null object reference
</strong>
</summary>

```shell
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String javax.xml.bind.DatatypeConverterInterface.printBase64Binary(byte[])' on a null object reference
        at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:547)
        at com.aliyuncs.auth.HmacSHA1Signer.signString(HmacSHA1Signer.java:22)
        at com.aliyuncs.RpcAcsRequest.signRequest(RpcAcsRequest.java:158)
        at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:268)
        at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:192)
        at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:85)
        at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:114)
        at albb.ecs.PageKeyedEcsDataSource.loadInitial(PageKeyedEcsDataSource.kt:49)
        at androidx.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:339)
        at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:175)
        at androidx.paging.PagedList.create(PagedList.java:216)
        at androidx.paging.PagedList$Builder.build(PagedList.java:388)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
        at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
</details>

My investigation result is : ``HmacSHA1Signer`` uses ``javax.xml.bind.DatatypeConverter`` to sign the request, which is not integrated in Android SDK (there is no default JAXB Provider available, and event if I try my custom implementation of ``DatatypeConverterInterface``, the interface is not found in Android system code).

So I try my own ``Signer`` method: 

```java
public class MySigner extends Signer {

  public static final String ENCODING = "UTF-8";
  private static final String ALGORITHM_NAME = "HmacSHA1";

  @Override
  public String signString(String stringToSign, String accessKeySecret) {
    try {
      Mac mac = Mac.getInstance(ALGORITHM_NAME);
      mac.init(new SecretKeySpec(accessKeySecret.getBytes(ENCODING), ALGORITHM_NAME));
      byte[] signData = mac.doFinal(stringToSign.getBytes(ENCODING));
      String signed = new String(Base64.encodeBase64(signData));
      Log.w("ALBB:Signed", "result: " + signed);
      return signed.trim();
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalArgumentException(e.toString());
    } catch (UnsupportedEncodingException e) {
      throw new IllegalArgumentException(e.toString());
    } catch (InvalidKeyException e) {
      throw new IllegalArgumentException(e.toString());
    }
  }

  @Override
  public String signString(String stringToSign, AlibabaCloudCredentials credentials) {
    return signString(stringToSign, credentials.getAccessKeySecret());
  }

  @Override
  public String getSignerName() {
    return "HMAC-SHA1";
  }

  @Override
  public String getSignerVersion() {
    return "1.0";
  }

  @Override
  public String getSignerType() {
    return null;
  }
}
```

And customize the AcsClient as below:

```java
public class MyAcsClient extends DefaultAcsClient {

  public MyAcsClient(IClientProfile profile) {
    super(profile);
  }

  // Override this to provide my custom signing mechanism
  @Override
  public <T extends AcsResponse> HttpResponse doAction(AcsRequest<T> request, boolean autoRetry,
      int maxRetryCounts, IClientProfile profile) throws ClientException {
    if (null == profile) {
      throw new ClientException("SDK.InvalidProfile", "No active profile found.");
    }

    String region = profile.getRegionId();
    if (null == request.getSysRegionId()) {
      request.setSysRegionId(region);
    }
    
    // Here
    Signer signer = new MySigner();
    FormatType format = profile.getFormat();
    return this.doAction(request, autoRetry, maxRetryCounts, request.getSysRegionId(),
        profile.getCredential(), signer,
        format);
  }
}
```

And use ``MyAcsClient`` instead of ``DefaultAcsClient``

```java
IAcsClient client = MyAcsClient(profile)
```

Using this, it can sign the request, but the request failed with the following error:

<details>
<summary>
<strong>
Caused by: com.aliyuncs.exceptions.ClientException: IncompleteSignature : The request signature does not conform to Aliyun standards
</strong>
</summary>

```shell
java.lang.Error: com.aliyuncs.exceptions.ClientException: IncompleteSignature : The request signature does not conform to Aliyun standards. server string to sign is:POST&%2F&AccessKeyId%3D<removed_on_purpose>%26Action%3DDescribeInstances%26Format%3DJSON%26PageNumber%3D1%26PageSize%3D15%26RegionId%3Dap-northeast-1%26ServiceCode%3Decs%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3De704d01c-7ee3-4d75-95ce-21731551765c1559782738166951%26SignatureVersion%3D1.0%26Timestamp%3D2019-06-06T00%253A58%253A58Z%26Version%3D2014-05-26
    RequestId : 24EF2DDC-AEBD-4DC3-B01F-80EB3D75AEF6
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.aliyuncs.exceptions.ClientException: IncompleteSignature : The request signature does not conform to Aliyun standards. server string to sign is:POST&%2F&AccessKeyId%3D<removed_on_purpose>%26Action%3DDescribeInstances%26Format%3DJSON%26PageNumber%3D1%26PageSize%3D15%26RegionId%3Dap-northeast-1%26ServiceCode%3Decs%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3De704d01c-7ee3-4d75-95ce-21731551765c1559782738166951%26SignatureVersion%3D1.0%26Timestamp%3D2019-06-06T00%253A58%253A58Z%26Version%3D2014-05-26
    RequestId : 24EF2DDC-AEBD-4DC3-B01F-80EB3D75AEF6
        at com.aliyuncs.DefaultAcsClient.parseAcsResponse(DefaultAcsClient.java:218)
        at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:115)
        at PageKeyedEcsDataSource.loadInitial(PageKeyedEcsDataSource.kt:49)
        at androidx.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:339)
        at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:175)
        at androidx.paging.PagedList.create(PagedList.java:216)
        at androidx.paging.PagedList$Builder.build(PagedList.java:388)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
        at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        	... 2 more
```
</details>

So my questions are:

- How can I correctly sign the request on Android? I tried various attempts to encode the base64 String but no success.

- Can you provide an implementation of IHttpClient using OkHttp?
- Can you not using classes from ``javax.xml.bind`` and ``com.apache`` package in the implementation to make it more Android friendly?

Thanks in advance.

**Comment by eneim** [comment]
I found that my request was a ``GET`` but the "server string to sign" (in the error message) is a ``POST`` request.

**Comment by atptro** [comment]
you can change to post request. The problem may be that the request body contains data.

**Comment by eneim** [comment]
@atptro got it. Also any plan to implement the http client using OkHttp?

**Comment by chen645800876** [comment]
![40e1bdf117509efc8c2a7a4dec3019e](https://user-images.githubusercontent.com/24761804/70420621-17d44480-1aa3-11ea-9349-1f34c2666a45.jpg)
调用的`httpclient`也是开源的，解决方法就是把`AllowAllHostnameVerifier`这个类名改了
