### ISSUE TITLE
 SDK.ServerUnreachable : Server unreachable: org.apache.http.conn.UnsupportedSchemeException

### ISSUE THREAD

**Issue by einverne** [aliyun/aliyun-openapi-java-sdk#259]
When using 

      <dependency>
        <groupId>com.aliyun</groupId>
        <artifactId>aliyun-java-sdk-core</artifactId>
        <version>4.0.2</version>
      </dependency>
      <dependency>
        <groupId>com.aliyun</groupId>
        <artifactId>aliyun-java-sdk-saf</artifactId>
        <version>1.0.2</version>
      </dependency>

by calling:

      ExecuteRequestResponse response = client.getAcsResponse(request);

```
com.aliyuncs.exceptions.ClientException: SDK.ServerUnreachable : Server unreachable: org.apache.http.conn.UnsupportedSchemeException: https pr
otocol is not supported
        at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:292)
        at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:209)
        at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:93)
        at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:137)


Caused by: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:109)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

```

**Comment by 13700294518** [comment]
Have you solved it？I also met this problem, Can you share it？
