### ISSUE TITLE
OSSUtils 加载 ExceptionInInitializerError

### ISSUE THREAD

**Issue by KehwZwei** [aliyun/aliyun-openapi-java-sdk#28]
`at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.MissingResourceException: Can't find bundle for base name common, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
        at com.aliyun.oss.common.utils.ResourceManager.<init>(ResourceManager.java:33)
        at com.aliyun.oss.common.utils.ResourceManager.getInstance(ResourceManager.java:37)
        at com.aliyun.oss.internal.OSSUtils.<clinit>(OSSUtils.java:54)
        ... 38 more`

用的
`
		<dependency>
			<groupId>com.aliyun.oss</groupId>
			<artifactId>aliyun-sdk-oss</artifactId>
		</dependency>`
version : 2.2.3

**Comment by gaort** [comment]
@KehwZwei 
您好，oss相关的问题，还请您移步
https://github.com/aliyun/aliyun-oss-java-sdk
