### ISSUE TITLE
调用javax.xml.bind.DatatypeConverter错误，查看到rt.jar(jdk 1.8)中的代码和项目依赖(jaxb-api 2.1)中的代码不一致

### ISSUE THREAD

**Issue by monkey1993** [aliyun/aliyun-openapi-java-sdk#282]
报错信息如下：

java.lang.NullPointerException
	at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:547)
	at com.aliyuncs.auth.HmacSHA1Signer.signString(HmacSHA1Signer.java:22)
	at com.aliyuncs.RpcAcsRequest.signRequest(RpcAcsRequest.java:158)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:265)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:192)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:85)
	at com.aliyuncs.DefaultAcsClient.getCommonResponse(DefaultAcsClient.java:152)
	at com.wuxia.base.util.CommonUtil.sendMsgByAliYunServer(CommonUtil.java:467)

rt.jar中代码：

    /**
     * <p>
     * Converts an array of bytes into a string.
     * @param val
     *     An array of bytes
     * @return
     *     A string containing a lexical representation of xsd:base64Binary
     * @throws IllegalArgumentException if <tt>val</tt> is null.
     */
    public static String printBase64Binary( byte[] val ) {
        if (theConverter == null) initConverter();
        return theConverter.printBase64Binary( val );
    }

jaxb-api 2.1 依赖中代码：

    /**
     * <p>
     * Converts an array of bytes into a string.
     * @param val
     *     An array of bytes
     * @return
     *     A string containing a lexical representation of xsd:base64Binary
     * @throws IllegalArgumentException if <tt>val</tt> is null.
     */ 
    public static String printBase64Binary( byte[] val ) {
        return theConverter.printBase64Binary( val );
    }

运行环境：CentOS Linux release 7.5.1804 (Core)
jdk：openjdk-10

**Comment by atptro** [comment]
可以强制依赖rt.jar中的javax版本，解决冲突问题
