### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by zhaojc** [aliyun/aliyun-openapi-java-sdk#360]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/impl/client/HttpClientBuilder
	at com.aliyuncs.http.clients.ApacheHttpClient.initHttpClientBuilder(ApacheHttpClient.java:148)
	at com.aliyuncs.http.clients.ApacheHttpClient.init(ApacheHttpClient.java:176)
	at com.aliyuncs.http.HttpClientFactory.buildClient(HttpClientFactory.java:41)
	at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:79)
	at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:68)
	at com.boraji.tutorial.springboot.MainApp.test(MainApp.java:23)
	at com.boraji.tutorial.springboot.MainApp.main(MainApp.java:16)
Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClientBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by atptro** [comment]
If maven is not downloading jar packages from a central repository, you need to add this dependency in the pom.xml file
<dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.10</version>
        </dependency>
