### ISSUE TITLE
SDK 无法解析 CS/clusters 接口的回复

### ISSUE THREAD

**Issue by huangd0ng** [aliyun/aliyun-openapi-java-sdk#362]
* **产品和接口**: CS/clusters
* **平台**: 平台无关
* **最小代码**:
因 sdk 中容器集群相关 API 封装为空实现（这一点也望得到改善。。。），所以自己实现如下：
```java
  public class DescribeClustersRequest extends RoaAcsRequest<Clusters.DescribeClustersResponse> {

    public DescribeClustersRequest() {
      super("CS", "2015-12-15", "DescribeClusters");
      this.setUriPattern("/clusters");
      this.setMethod(MethodType.GET);
    }

    @Override
    public Class<DescribeClustersResponse> getResponseClass() {
      return DescribeClustersResponse.class;
    }
  }

  DescribeClustersRequest request = new Clusters.DescribeClustersRequest();
  DescribeClustersResponse response = client.getAcsResponse(request);
```
抛出异常：
```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 33
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[na:na]
	at java.base/java.lang.String.substring(String.java:1874) ~[na:na]
	at com.aliyuncs.reader.JsonReader.processArray(JsonReader.java:275) ~[aliyun-java-sdk-core-4.4.1.jar:na]
	at com.aliyuncs.reader.JsonReader.readJson(JsonReader.java:109) ~[aliyun-java-sdk-core-4.4.1.jar:na]
	at com.aliyuncs.reader.JsonReader.read(JsonReader.java:72) ~[aliyun-java-sdk-core-4.4.1.jar:na]
	at com.aliyuncs.reader.JsonReader.read(JsonReader.java:49) ~[aliyun-java-sdk-core-4.4.1.jar:na]
	at com.aliyuncs.DefaultAcsClient.readResponse(DefaultAcsClient.java:340) ~[aliyun-java-sdk-core-4.4.1.jar:na]
	at com.aliyuncs.DefaultAcsClient.parseAcsResponse(DefaultAcsClient.java:199) ~[aliyun-java-sdk-core-4.4.1.jar:na]
	at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:115) ~[aliyun-java-sdk-core-4.4.1.jar:na]
```

原因：
该接口回复根元素为数组(https://help.aliyun.com/document_detail/90774.html)：
```json
[
    {
        "agent_version": "string",
        "cluster_id": "string",
        "created": "datetime",
        "external_loadbalancer_id": "string",
        "master_url": "string",
        "name": "string",
        "network_mode": "string",
        "region_id": "string",
        "security_group_id": "string",
        "size": "numbers",
        "state": "string",
        "updated": "datetime",
        "vpc_id": "string",
        "vswitch_id": "string"
    }
]
```
触发代码：
```java
 private void processArray(String baseKey) {
        int index = 0;
        // 此时为根元素，baseKey 为 "DescribeClustersRequest"，不包含 "."
        String preKey = baseKey.substring(0, baseKey.lastIndexOf("."));
```

**Comment by atptro** [comment]
这个是cs产品配置问题 需要用HttpResponse response = client.doAction(request); 方式接受返回并解析返回
