### ISSUE TITLE
DescribeInstances endpoint error

### ISSUE THREAD

**Issue by liuyangc3** [aliyun/aliyun-openapi-java-sdk#387]
* **Product and API**: DescribeInstances
* **Platform**: Linux Ubuntu 1804 TLS
* **Mininum Code**:  see below
groovy code
```groovy
@Grab(group = 'com.aliyun', module = 'aliyun-java-sdk-core', version = '4.4.9')
@Grab(group = 'com.aliyun', module = 'aliyun-java-sdk-ecs', version = '4.18.0')
import com.aliyuncs.DefaultAcsClient
import com.aliyuncs.IAcsClient
import com.aliyuncs.exceptions.ServerException
import com.aliyuncs.profile.DefaultProfile
import com.aliyuncs.ecs.model.v20140526.*
import groovy.json.JsonOutput


def profile = DefaultProfile.getProfile("cn-zhangjiakou", accessKey, accessSecret)
client = new DefaultAcsClient(profile)

def instanceIds = JsonOutput.toJson(["i-xxxxxxxxxx"])
def request = new DescribeInstancesRequest();
request.setRegionId("cn-zhangjiakou")
request.setInstanceIds(instanceIds)

try {
    def response = client.getAcsResponse(request)
    def instance = response.instances[0]
    println instance
} catch (ServerException e) {
    e.printStackTrace()
}
```

the stacktrace
```
 java.net.UnknownHostException: ecs..aliyuncs.com: Name or service not known
.....
com.aliyuncs.exceptions.ClientException: SDK.ServerUnreachable : Server unreachable: connection http://ecs..aliyuncs.com/?SignatureVersion=1.0&Action=DescribeInstances&ServiceCode=ecs&Format=JSON&SignatureNonce=b57a81c1-e8c1-407e-94b7-3fa391ee228a15795315202013146&Version=2014-05-26&AccessKeyId=LT........v7&Signature=Bk7fId6z6p1oB%2Fd%2BKM1e4iQZeXc%3D&SignatureMethod=HMAC-SHA1&RegionId=&InstanceIds=%5B%22%22%5D&Timestamp=2020-01-20T14%3A45%3A20Z failed
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:303)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:194)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:87)
```

**Comment by atptro** [comment]
Try adding a line of code: request.setEndpoint("ecs.cn-zhangjiakou.aliyuncs.com")
