### ISSUE TITLE
获取emr集群信息报错 SDK.InvalidRegionId : Can not find endpoint to access

### ISSUE THREAD

**Issue by ziFieYu** [aliyun/aliyun-openapi-java-sdk#50]
获取emr集群信息报错 SDK.InvalidRegionId : Can not find endpoint to access

我的regionid应该是没有问题的，
accesskeyid和accesskeysecret在日志服务里面都可以使用，所以感觉这边应该也没有问题

但是获取emr集群信息的时候回报错误
com.aliyuncs.exceptions.ClientException: SDK.InvalidRegionId : Can not find endpoint to access.
  at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:261)
  at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:207)
  at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:100)
  at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:144)
  at com.vip.bigdata.util.emr.EmrUtils$.getClusterInfo(EmrUtils.scala:80)
  ... 48 elided

**Comment by Qingtang-SDK** [comment]
感谢你的反馈，我们已经在最新版本中解决了这一问题。请看：
https://yq.aliyun.com/ask/416179
