### ISSUE TITLE
SDK核心库 设置连接时发生 java.lang.NoSuchMethodError: com.google.gson.JsonObject.keySet()Ljava/util/Set;

### ISSUE THREAD

**Issue by autohawkeye** [aliyun/aliyun-openapi-java-sdk#60]
最新版本的SDK
<dependency>
    <groupId>com.aliyun</groupId>
    <artifactId>aliyun-java-sdk-core</artifactId>
    <version>4.1.2</version>
</dependency>

走到这一步（IAcsClient client = new DefaultAcsClient(profile);）的时候报下面的错误

Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.JsonObject.keySet()Ljava/util/Set;
	at com.aliyuncs.endpoint.LocalConfigRegionalEndpointResolver.initRegionalEndpointData(LocalConfigRegionalEndpointResolver.java:64)
	at com.aliyuncs.endpoint.LocalConfigRegionalEndpointResolver.initLocalConfig(LocalConfigRegionalEndpointResolver.java:53)
	at com.aliyuncs.endpoint.LocalConfigRegionalEndpointResolver.<init>(LocalConfigRegionalEndpointResolver.java:43)
	at com.aliyuncs.endpoint.DefaultEndpointResolver.<init>(DefaultEndpointResolver.java:42)
	at com.aliyuncs.endpoint.DefaultEndpointResolver.<init>(DefaultEndpointResolver.java:54)
	at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:81)
	at com.aliyuncs.DefaultAcsClient.<init>(DefaultAcsClient.java:69)

**Comment by allenunique** [comment]
同样的问题

**Comment by Qingtang-SDK** [comment]
你好，这个问题我们已经收到，解决进展将会及时同步。

**Comment by allenunique** [comment]
加上这个依赖就好了，
		
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.5</version>
		</dependency>

**Comment by kndylau** [comment]
请问这个问题解决了吗？

**Comment by JacksonTian** [comment]
@kndylau 请参考 @allenunique 的方案。

**Comment by lihuadong** [comment]
项目中引入了 gson这个jar包 。依然提示楼上的错误。

**Comment by lihuadong** [comment]
@JacksonTian   @kndylau  上面的问题我已经解决了。解决思路如下：找了干净的环境，只使用aliyun-core-sdk 和 gson 这两个包，没有问题，后来怀疑是包冲突。把项目中的gson 都换成新的包。问题解决。

**Comment by xiaoyaojian** [comment]
按照@allenunique 的做法，现在可以了，但是我在另外一个系统上不用更新到2.8.5也可以工作，很奇怪，原始版本应该是2.8.0

**Comment by liukaihui** [comment]
到自己的maven本地仓库com\google\code\gson\gson下,看看是不是有两个或者多个版本关于json的,将老的给删除就行了,并且要记得看看项目中有没有其他的地方引入老版本的依赖,要是有的话,将老版本的依赖改成新版本就完美解决了这个问题,前提要先导入2.8.5这个版本的jar
