### ISSUE TITLE
Parse Error for SAS's Plan Price

### ISSUE THREAD

**Issue by LipiLee** [aliyun/aliyun-openapi-java-sdk#702]
* **Product and API**: Simple Application Server and com.aliyun.swas_open20200601.models.ListPlansRequest
* **Platform**: 64-bit Windows
* **Minimum Code**:

### Parse Error for Plan Price

**Please check the below exception log,**

Exception in thread "main" com.aliyun.tea.TeaException
	at com.aliyun.tea.TeaModel.setTeaModelField(TeaModel.java:205)
	at com.aliyun.tea.TeaModel.toModel(TeaModel.java:176)
	at com.aliyun.swas_open20200601.Client.listPlansWithOptions(Client.java:208)
	at com.aliyun.swas_open20200601.Client.listPlans(Client.java:213)
	at AlibabaCloudKt.listPlans(AlibabaCloud.kt:99)
	at AlibabaCloudKt.main(AlibabaCloud.kt:36)
Caused by: com.aliyun.tea.TeaException
	at com.aliyun.tea.TeaModel.setTeaModelField(TeaModel.java:205)
	at com.aliyun.tea.TeaModel.toModel(TeaModel.java:176)
	at com.aliyun.tea.TeaModel.setTeaModelField(TeaModel.java:192)
	... 5 more
Caused by: com.aliyun.tea.TeaException
	at com.aliyun.tea.TeaModel.buildObject(TeaModel.java:146)
	at com.aliyun.tea.TeaModel.buildObject(TeaModel.java:134)
	at com.aliyun.tea.TeaModel.setTeaModelField(TeaModel.java:199)
	... 7 more
Caused by: com.aliyun.tea.TeaException
	at com.aliyun.tea.TeaModel.setTeaModelField(TeaModel.java:205)
	at com.aliyun.tea.TeaModel.toModel(TeaModel.java:176)
	at com.aliyun.tea.TeaModel.buildObject(TeaModel.java:144)
	... 9 more
**Caused by: java.lang.NumberFormatException: For input string: "$3.5"**
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:556)
	at com.aliyun.tea.TeaModel.confirmType(TeaModel.java:383)
	at com.aliyun.tea.TeaModel.setTeaModelField(TeaModel.java:201)
	... 11 more

**Comment by LipiLee** [comment]
This issue's repo changed to https://github.com/aliyun/alibabacloud-java-sdk.git
