### ISSUE TITLE
获取容器服务的应用实例列表异常

### ISSUE THREAD

**Issue by wolcengit** [aliyun/aliyun-openapi-java-sdk#71]
aliyun-java-sdk-core-3.5.0
aliyun-java-sdk-cs-2.1.0
获取容器服务的应用实例列表异常
```java
        GetClusterProjectsRequest request = new GetClusterProjectsRequest();
        request.setClusterId(clusterId);
        GetClusterProjectsResponse response;
        try {
            response = client.getAcsResponse(request);
            System.out.println(JSON.toJSONString(response,true));
       } catch (ServerException e) {
            e.printStackTrace();
        } catch (ClientException e) {
            e.printStackTrace();
        }
```
异常结果如下：
```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.aliyuncs.reader.JsonReader.processArray(JsonReader.java:270)
	at com.aliyuncs.reader.JsonReader.readJson(JsonReader.java:117)
	at com.aliyuncs.reader.JsonReader.read(JsonReader.java:80)
	at com.aliyuncs.reader.JsonReader.read(JsonReader.java:58)
	at com.aliyuncs.DefaultAcsClient.readResponse(DefaultAcsClient.java:297)
	at com.aliyuncs.DefaultAcsClient.parseAcsResponse(DefaultAcsClient.java:197)
	at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:124)
	at Test.getProjects(Test.java:30)
	at Test.main(Test.java:22)

Process finished with exit code 1
```
调试：
在类 DefaultAcsClient.java  行295 已经截取
        String responseEndpoint = clasz.getName().substring(clasz.getName().lastIndexOf(".") + 1);
在类 JsonReader.java 行 270再次去截取，异常
       String preKey = baseKey.substring(0, baseKey.lastIndexOf("."));

使用源码
aliyun-java-sdk-core-4.2.2
aliyun-java-sdk-cs-2.9.0
问题依旧在，修改 类 JsonReader.java 行 270为String preKey = baseKey;后解析生成map成功，后续返回空值，发现类GetClusterProjectsResponseUnmarshaller.java没有实现

**唉o(︶︿︶)o 唉**

**Comment by atptro** [comment]
好的，看到您的问题了，稍后我们会去跟踪修改

**Comment by ssy352959096** [comment]
你好,在 cs 这边对于 SDK 的使用是非常特殊的，产品方允许使用sdk生成的 Request ,但没有使用对应的 response 去接收返回的数据;你可以使用client 的 doAction 办法接收返回数据;

**Comment by ssy352959096** [comment]
1.在最新版的core已经修复了第一个问题;
2.第二个问题是由于cs产品方的要求,没有使用对应的 response 去接收返回的数据,也就是说在类GetClusterProjectsResponseUnmarshaller中没有去实现对GetClusterProjectsResponse的封装;
根据您给的示例我们推荐您使用下面方法:
GetClusterProjectsRequest request = new GetClusterProjectsRequest();
        request.setClusterId(clusterId);
        HttpResponse response;
        try {
            response = this.client.doAction(request);
            System.out.println(JSON.toJSONString(response,true));
        } catch (ServerException e) {
            e.printStackTrace();
        } catch (ClientException e) {
            e.printStackTrace();
        }
